### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by kakaluote** [t0rakka/mango-examples#4]
i change the jpeg_benchmark, compile by   g++ -std=c++11 benchmark.cpp
and got this error

```
In file included from /usr/local/include/mango/core/core.hpp:10:0,
                 from /usr/local/include/mango/mango.hpp:7,
                 from benchmark.cpp:5:
/usr/local/include/mango/core/bits.hpp: In function ‘constexpr int mango::modulo(int, int)’:
/usr/local/include/mango/core/bits.hpp:159:5: error: body of constexpr function ‘constexpr int mango::modulo(int, int)’ not a return-statement
     }
```

error in mango.hpp? I compile mango success

**Comment by kakaluote** [comment]
i got some reasons, is that mango must compile with c++14?

**Comment by t0rakka** [comment]
Short answer: yes. Longer answer: we use c++17 internally in-house and migrating MANGO to C++17 would simplify memory management: The C++17 supports alignment / alignas for dynamic memory allocations which is a Big Deal for SIMD programming. Currently we have to resort to custom hackery to get aligned memory blocks. The simplest approach is to use custom aligned memory allocator so that we can use std containers like std::vector, std::list, std::map and others and the data will be correctly aligned. The custom allocator does disable nearly all optimizations for the containers so the code becomes really slow; construction overhead kills performance for some critical paths.. so we work around that by using the mango::Buffer and mango::AlignedPointer helpers, but that's far from ideal solution.

So we're actually looking forward to migrating to C++17, not C++11, just for this one feature. :_) 

You should make a fork and modify it until it compiles w/o c++14, but warning: will not accept PRs that go backwards..
